# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0002_auto_20170704_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='change',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='change_perc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='last_update',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apidata',
            name='market_cap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
